/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/ai-talk/': RouteRecordInfo<
      '/ai-talk/',
      '/ai-talk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps/': RouteRecordInfo<
      '/apps/',
      '/apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/confirm'
      | '/auth/forgot-password'
      | '/auth/otp'
      | '/auth/sign-in'
      | '/auth/sign-in-2'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/confirm': RouteRecordInfo<
      '/auth/confirm',
      '/auth/confirm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/otp': RouteRecordInfo<
      '/auth/otp',
      '/auth/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in-2': RouteRecordInfo<
      '/auth/sign-in-2',
      '/auth/sign-in-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/billing/': RouteRecordInfo<
      '/billing/',
      '/billing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/accessories': RouteRecordInfo<
      '/dashboard/accessories',
      '/dashboard/accessories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/agent-infra': RouteRecordInfo<
      '/dashboard/agent-infra',
      '/dashboard/agent-infra',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/agents/': RouteRecordInfo<
      '/dashboard/agents/',
      '/dashboard/agents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/agents/[id]': RouteRecordInfo<
      '/dashboard/agents/[id]',
      '/dashboard/agents/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/apis': RouteRecordInfo<
      '/dashboard/apis',
      '/dashboard/apis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/banners': RouteRecordInfo<
      '/dashboard/banners',
      '/dashboard/banners',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/changes': RouteRecordInfo<
      '/dashboard/changes',
      '/dashboard/changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/colors': RouteRecordInfo<
      '/dashboard/colors',
      '/dashboard/colors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/cron': RouteRecordInfo<
      '/dashboard/cron',
      '/dashboard/cron',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/design-memory': RouteRecordInfo<
      '/dashboard/design-memory',
      '/dashboard/design-memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/docs': RouteRecordInfo<
      '/dashboard/docs',
      '/dashboard/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/model-pages': RouteRecordInfo<
      '/dashboard/model-pages',
      '/dashboard/model-pages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/oems': RouteRecordInfo<
      '/dashboard/oems',
      '/dashboard/oems',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/offers': RouteRecordInfo<
      '/dashboard/offers',
      '/dashboard/offers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/onboarding': RouteRecordInfo<
      '/dashboard/onboarding',
      '/dashboard/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/onboarding-docs': RouteRecordInfo<
      '/dashboard/onboarding-docs',
      '/dashboard/onboarding-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/operations': RouteRecordInfo<
      '/dashboard/operations',
      '/dashboard/operations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/page-builder/': RouteRecordInfo<
      '/dashboard/page-builder/',
      '/dashboard/page-builder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/page-builder/[slug]': RouteRecordInfo<
      '/dashboard/page-builder/[slug]',
      '/dashboard/page-builder/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/dashboard/page-builder-docs': RouteRecordInfo<
      '/dashboard/page-builder-docs',
      '/dashboard/page-builder-docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/portal-assets': RouteRecordInfo<
      '/dashboard/portal-assets',
      '/dashboard/portal-assets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/portals': RouteRecordInfo<
      '/dashboard/portals',
      '/dashboard/portals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/pricing': RouteRecordInfo<
      '/dashboard/pricing',
      '/dashboard/pricing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/products': RouteRecordInfo<
      '/dashboard/products',
      '/dashboard/products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/runs': RouteRecordInfo<
      '/dashboard/runs',
      '/dashboard/runs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/settings/ai-models': RouteRecordInfo<
      '/dashboard/settings/ai-models',
      '/dashboard/settings/ai-models',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/settings/regeneration': RouteRecordInfo<
      '/dashboard/settings/regeneration',
      '/dashboard/settings/regeneration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/source-pages': RouteRecordInfo<
      '/dashboard/source-pages',
      '/dashboard/source-pages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/variants': RouteRecordInfo<
      '/dashboard/variants',
      '/dashboard/variants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help-center': RouteRecordInfo<
      '/help-center',
      '/help-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/': RouteRecordInfo<
      '/marketing/',
      '/marketing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/hello': RouteRecordInfo<
      '/marketing/hello',
      '/marketing/hello',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/display': RouteRecordInfo<
      '/settings/display',
      '/settings/display',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sva-components/': RouteRecordInfo<
      '/sva-components/',
      '/sva-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks/': RouteRecordInfo<
      '/tasks/',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/ai-talk/index.vue': {
      routes:
        | '/ai-talk/'
      views:
        | never
    }
    'src/pages/apps/index.vue': {
      routes:
        | '/apps/'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/confirm'
        | '/auth/forgot-password'
        | '/auth/otp'
        | '/auth/sign-in'
        | '/auth/sign-in-2'
        | '/auth/sign-up'
      views:
        | 'default'
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/confirm.vue': {
      routes:
        | '/auth/confirm'
      views:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'src/pages/auth/otp.vue': {
      routes:
        | '/auth/otp'
      views:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
    }
    'src/pages/auth/sign-in-2.vue': {
      routes:
        | '/auth/sign-in-2'
      views:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
    }
    'src/pages/billing/index.vue': {
      routes:
        | '/billing/'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/accessories.vue': {
      routes:
        | '/dashboard/accessories'
      views:
        | never
    }
    'src/pages/dashboard/agent-infra.vue': {
      routes:
        | '/dashboard/agent-infra'
      views:
        | never
    }
    'src/pages/dashboard/agents/index.vue': {
      routes:
        | '/dashboard/agents/'
      views:
        | never
    }
    'src/pages/dashboard/agents/[id].vue': {
      routes:
        | '/dashboard/agents/[id]'
      views:
        | never
    }
    'src/pages/dashboard/apis.vue': {
      routes:
        | '/dashboard/apis'
      views:
        | never
    }
    'src/pages/dashboard/banners.vue': {
      routes:
        | '/dashboard/banners'
      views:
        | never
    }
    'src/pages/dashboard/changes.vue': {
      routes:
        | '/dashboard/changes'
      views:
        | never
    }
    'src/pages/dashboard/colors.vue': {
      routes:
        | '/dashboard/colors'
      views:
        | never
    }
    'src/pages/dashboard/cron.vue': {
      routes:
        | '/dashboard/cron'
      views:
        | never
    }
    'src/pages/dashboard/design-memory.vue': {
      routes:
        | '/dashboard/design-memory'
      views:
        | never
    }
    'src/pages/dashboard/docs.vue': {
      routes:
        | '/dashboard/docs'
      views:
        | never
    }
    'src/pages/dashboard/model-pages.vue': {
      routes:
        | '/dashboard/model-pages'
      views:
        | never
    }
    'src/pages/dashboard/oems.vue': {
      routes:
        | '/dashboard/oems'
      views:
        | never
    }
    'src/pages/dashboard/offers.vue': {
      routes:
        | '/dashboard/offers'
      views:
        | never
    }
    'src/pages/dashboard/onboarding.vue': {
      routes:
        | '/dashboard/onboarding'
      views:
        | never
    }
    'src/pages/dashboard/onboarding-docs.vue': {
      routes:
        | '/dashboard/onboarding-docs'
      views:
        | never
    }
    'src/pages/dashboard/operations.vue': {
      routes:
        | '/dashboard/operations'
      views:
        | never
    }
    'src/pages/dashboard/page-builder/index.vue': {
      routes:
        | '/dashboard/page-builder/'
      views:
        | never
    }
    'src/pages/dashboard/page-builder/[slug].vue': {
      routes:
        | '/dashboard/page-builder/[slug]'
      views:
        | never
    }
    'src/pages/dashboard/page-builder-docs.vue': {
      routes:
        | '/dashboard/page-builder-docs'
      views:
        | never
    }
    'src/pages/dashboard/portal-assets.vue': {
      routes:
        | '/dashboard/portal-assets'
      views:
        | never
    }
    'src/pages/dashboard/portals.vue': {
      routes:
        | '/dashboard/portals'
      views:
        | never
    }
    'src/pages/dashboard/pricing.vue': {
      routes:
        | '/dashboard/pricing'
      views:
        | never
    }
    'src/pages/dashboard/products.vue': {
      routes:
        | '/dashboard/products'
      views:
        | never
    }
    'src/pages/dashboard/runs.vue': {
      routes:
        | '/dashboard/runs'
      views:
        | never
    }
    'src/pages/dashboard/settings/ai-models.vue': {
      routes:
        | '/dashboard/settings/ai-models'
      views:
        | never
    }
    'src/pages/dashboard/settings/regeneration.vue': {
      routes:
        | '/dashboard/settings/regeneration'
      views:
        | never
    }
    'src/pages/dashboard/source-pages.vue': {
      routes:
        | '/dashboard/source-pages'
      views:
        | never
    }
    'src/pages/dashboard/variants.vue': {
      routes:
        | '/dashboard/variants'
      views:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
    }
    'src/pages/help-center.vue': {
      routes:
        | '/help-center'
      views:
        | never
    }
    'src/pages/marketing/index.vue': {
      routes:
        | '/marketing/'
      views:
        | never
    }
    'src/pages/marketing/hello.vue': {
      routes:
        | '/marketing/hello'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
    }
    'src/pages/settings/display.vue': {
      routes:
        | '/settings/display'
      views:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
    }
    'src/pages/sva-components/index.vue': {
      routes:
        | '/sva-components/'
      views:
        | never
    }
    'src/pages/tasks/index.vue': {
      routes:
        | '/tasks/'
      views:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
