import { readFileSync } from 'node:fs'
import { describe, expect, it, vi } from 'vitest'

import { resolvePublicationPreviewView } from '@/composables/use-model-page-publication'

vi.mock('@/lib/worker-api', () => ({}))

describe('preview Tailwind conversion toolbar', () => {
  it('keeps the public preview read-only and does not expose authenticated publication controls', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('import { useAuthStore } from \'@/stores/auth\'')
    expect(source).toContain('const canAdministerPreview = computed(() => authStore.isLogin)')
    expect(source).toContain('!canAdministerPreview.value || isWriteProtectedPage.value')
    expect(source).toContain('<PublicationControls\n          v-if="canAdministerPreview"')
    expect(source).toContain('if (canAdministerPreview.value)\n      await refreshPublicationState()')
    expect(source).toContain('v-if="canAdministerPreview"\n          class="inline-flex h-8 items-center')
  })

  it('redirects a direct stale candidate route before candidate HTML can render', () => {
    expect(resolvePublicationPreviewView('candidate', 'stale', null)).toBe('edit')
    expect(resolvePublicationPreviewView('candidate', 'ready', null)).toBe('edit')
    expect(resolvePublicationPreviewView('candidate', 'ready', 'blob:candidate-22')).toBe('candidate')
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')
    expect(source).toContain('enforceCandidatePreviewRoute()')
    expect(source).toContain('publication.status.value !== \'stale\' && publication.candidatePreviewUrl.value')
    expect(source).toContain('overflow-x-auto overflow-y-hidden whitespace-nowrap')
    expect(source).toContain('[&>*]:shrink-0')
  })

  it('converts the selected preview clone region in place without leaving clone mode', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')
    const convertFunction = source.slice(
      source.indexOf('async function convertSelectedCloneRegionToTailwind()'),
      source.indexOf('async function convertPageToTailwind()'),
    )

    expect(source).toContain('selectedCloneRegionData')
    expect(source).toContain('const selectedCloneRegion = computed')
    expect(source).toContain('const canConvertSelectedCloneRegion = computed')
    expect(source).toContain('const convertingCloneRegion = ref(false)')
    expect(source).toContain('async function convertSelectedCloneRegionToTailwind()')
    expect(convertFunction).toContain('buildPreviewReplacementHtmlFromCloneRegion({')
    expect(source).toContain('tailwindRecipeArtifact: selectedCloneRegion.value?.tailwindRecipeArtifact')
    expect(source).toContain('compileTailwindRecipeArtifact')
    expect(source).toContain('fetchStyleGuide')
    expect(convertFunction).toContain('patchCloneField({')
    expect(convertFunction).toContain('kind: \'outer-html\'')
    expect(convertFunction).toContain('html: replacementHtml')
    expect(convertFunction).not.toContain('addSectionFromLiveData')
    expect(convertFunction).not.toContain('setActiveMode(\'sections\')')
    expect(source).toContain('title="Convert selected region to Tailwind"')
    expect(source).toContain('Convert to Tailwind')
  })

  it('exposes whole-page Tailwind conversion as an unsaved structured draft', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')
    const convertPageFunction = source.slice(
      source.indexOf('async function convertPageToTailwind()'),
      source.indexOf('async function savePreview()'),
    )

    expect(source).toContain('convertCloneRegionsToTailwindSections')
    expect(source).toContain('const convertingPage = ref(false)')
    expect(source).toContain('const canConvertPageToTailwind = computed')
    expect(convertPageFunction).toContain('convertCloneRegionsToTailwindSections({')
    expect(convertPageFunction).toContain('failClosed: true')
    expect(convertPageFunction).toContain('if (result.blocked)')
    expect(convertPageFunction).toContain('toast.error(result.blocked.message)')
    expect(convertPageFunction).toContain('const collectedRegions = await pageBuilderCanvas.value?.collectCloneRegions()')
    expect(convertPageFunction).toContain('regions: collectedRegions?.length ? collectedRegions : cloneRegionsForSave.value')
    expect(convertPageFunction).toContain('replaceSections(result.sections)')
    expect(convertPageFunction).toContain('setActiveMode(\'sections\')')
    expect(convertPageFunction).toContain('toast.success')
    expect(convertPageFunction).not.toContain('saveSections(')
    expect(source).toContain('title="Convert page to Tailwind sections"')
    expect(source).toContain('Convert Page')
  })

  it('routes deterministic context-menu leaves to selected and whole-page conversion', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('action === \'convert-tailwind-selected\'')
    expect(source).toContain('action === \'convert-tailwind-all\'')
    expect(source).toContain('await replaceCloneRegionWithTailwind({ regionId, html, tailwindRecipeArtifact })')
    expect(source).toContain('await convertPageToTailwind()')
  })

  it('opens the fidelity assistant from the preview context menu without saving', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')
    const applyStart = source.indexOf('function applyFidelityCandidate')
    const applyEnd = source.indexOf('async function convertSelectedCloneRegionToTailwind', applyStart)
    const applySource = source.slice(applyStart, applyEnd)

    expect(source).toContain('action === \'match-oem\'')
    expect(source).toContain('buildEditableSectionFromCloneRegion({')
    expect(source).toContain('buildFidelityReferenceHtmlFromCloneRegion({')
    expect(source).toContain('extractTailwindRecipeArtifactCss(tailwindRecipeArtifact)')
    expect(source).toContain('<FidelityAssistantDialog')
    expect(source).toContain(':recipe-artifact="fidelityRecipeArtifact"')
    expect(source).toContain(':source-url="page?.source_url || \'\'"')
    expect(source).toContain('@apply="applyFidelityCandidate"')
    expect(applySource).toContain('addSectionFromLiveData(section)')
    expect(applySource).toContain('setActiveMode(\'sections\')')
    expect(applySource).not.toContain('saveSections(')
    expect(applySource).not.toContain('publication.buildCandidate()')
  })

  it('adds a read-only Tailwind source view for converted sections', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('type PreviewView = \'edit\' | \'production\' | \'candidate\' | \'source\' | \'compare\' | \'standalone\'')
    expect(source).toContain('const isSourceView = computed(() => previewView.value === \'source\')')
    expect(source).toContain('const hasTailwindSource = computed')
    expect(source).toContain('function tailwindSectionSource(section: any): string')
    expect(source).toContain('return raw === \'production\' || raw === \'candidate\' || raw === \'source\' || raw === \'compare\' || raw === \'standalone\' ? raw : \'edit\'')
    expect(source).toContain('query.view = \'source\'')
    expect(source).toContain('@click="setPreviewView(\'source\')"')
    expect(source).toContain('title="Tailwind source"')
    expect(source).toContain('Tailwind Source')
    expect(source).toContain('v-if="isSourceView"')
    expect(source).toContain('data-oem-tailwind-source-view="true"')
    expect(source).toContain('v-for="section in sections"')
    expect(source).toContain('tailwindSectionSource(section)')
    expect(source).toContain('/* Tailwind Compiler Summary */')
    expect(source).toContain('template_kind: conversion.template_kind')
    expect(source).toContain('computed_snapshots: conversion.stats?.computed_snapshots')
    expect(source).toContain('parity_risks: conversion.parity_risks || []')
    expect(source).toContain('/* Leftover CSS */')
    expect(source).toContain('/* Tailwind Conversion Stats */')
    expect(source).toContain('_tailwind_leftover_css')
    expect(source).toContain('_tailwind_conversion?.stats')
  })

  it('keeps Save Draft separate from candidate build and publication actions', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')
    const saveStart = source.indexOf('async function savePreview()')
    const saveEnd = source.indexOf('async function refreshPublicationState()', saveStart)
    const saveSource = source.slice(saveStart, saveEnd)

    expect(source).toContain('Save Draft')
    expect(source).toContain('useModelPagePublication')
    expect(source).toContain('@build-candidate="buildPublicationCandidate"')
    expect(source).toContain('@publish="publishCandidate"')
    expect(source).toContain('@rollback="rollbackPublication"')
    expect(source).toContain(':can-build="draftVersion != null && !publication.isLoading.value && !saving && !isDirty"')
    expect(saveSource).toContain('publication.markDraftChanged(page.value.version)')
    expect(saveSource).toContain('await publication.refresh()')
    expect(saveSource).not.toContain('publication.buildCandidate()')
    expect(saveSource).not.toContain('publication.publish()')
  })

  it('previews the authenticated candidate blob with responsive frame controls', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('type PreviewView = \'edit\' | \'production\' | \'candidate\' | \'source\' | \'compare\' | \'standalone\'')
    expect(source).toContain('const isCandidateView = computed(() => previewView.value === \'candidate\')')
    expect(source).toContain('query.view = \'candidate\'')
    expect(source).toContain('@preview-candidate="previewCandidate"')
    expect(source).toContain(':src="publication.candidatePreviewUrl.value || undefined"')
    expect(source).toContain('title="Candidate model page preview"')
    expect(source).toContain('sandbox="allow-scripts"')
    expect(source).toContain('title="Desktop candidate preview"')
    expect(source).toContain('title="Tablet candidate preview (768px)"')
    expect(source).toContain('title="Mobile candidate preview (375px)"')
  })

  it('adds a read-only Tailwind compare view for converted sections', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('type PreviewView = \'edit\' | \'production\' | \'candidate\' | \'source\' | \'compare\' | \'standalone\'')
    expect(source).toContain('const isCompareView = computed(() => previewView.value === \'compare\')')
    expect(source).toContain('import { Badge } from \'@/components/ui/badge\'')
    expect(source).toContain('import { Card, CardContent, CardDescription, CardHeader, CardTitle } from \'@/components/ui/card\'')
    expect(source).toContain('<Card')
    expect(source).toContain('<CardHeader')
    expect(source).toContain('<CardTitle')
    expect(source).toContain('<CardDescription')
    expect(source).toContain('<CardContent')
    expect(source).toContain('<Badge')
    expect(source).toContain('function comparePaneId(section: any, pane: \'original\' | \'converted\'): string')
    expect(source).toContain('function scrollComparePane(section: any, pane: \'original\' | \'converted\')')
    expect(source).toContain('@click="scrollComparePane(section, \'original\')"')
    expect(source).toContain('@click="scrollComparePane(section, \'converted\')"')
    expect(source).toContain(':id="comparePaneId(section, \'original\')"')
    expect(source).toContain(':id="comparePaneId(section, \'converted\')"')
    expect(source).toContain('type CompareLayoutMode = \'accurate\' | \'fit\'')
    expect(source).toContain('const compareLayoutMode = ref<CompareLayoutMode>(\'accurate\')')
    expect(source).toContain('@click="compareLayoutMode = \'accurate\'"')
    expect(source).toContain('@click="compareLayoutMode = \'fit\'"')
    expect(source).toContain('compareLayoutMode === \'fit\' ? \'grid gap-0 xl:grid-cols-2\' : \'grid gap-0 min-[2800px]:grid-cols-2\'')
    expect(source).toContain('compareLayoutMode === \'fit\' ? \'w-full bg-white\' : \'max-w-none min-w-[1280px] bg-white\'')
    expect(source).toContain('const hasTailwindCompare = computed')
    expect(source).toContain('function tailwindCompareOriginalHtml(section: any): string')
    expect(source).toContain('function tailwindCompareConvertedHtml(section: any): string')
    expect(source).toContain('function tailwindLeftoverCss(section: any): string')
    expect(source).toContain('function hasTailwindLeftoverCss(section: any): boolean')
    expect(source).toContain('function unsupportedDeclarationSamples(section: any): string[]')
    expect(source).toContain('function hasUnsupportedDeclarationSamples(section: any): boolean')
    expect(source).toContain('function tailwindCompareSrcdoc(html: string, label: string, section?: any): string')
    expect(source).toContain('function tailwindCompareViewportWidth(section: any): number')
    expect(source).toContain('function tailwindCompareViewportHeight(section: any): number')
    expect(source).toContain('min-w-[1280px]')
    expect(source).toContain('max-w-[1600px]')
    expect(source).toContain('min-[2800px]:grid-cols-2')
    expect(source).not.toContain('lg:grid-cols-2')
    expect(source).toContain('tailwindCompareViewportWidth(section)')
    expect(source).toContain('tailwindCompareViewportHeight(section)')
    expect(source).toContain('Original')
    expect(source).toContain('Converted Tailwind')
    expect(source).toContain('return raw === \'production\' || raw === \'candidate\' || raw === \'source\' || raw === \'compare\' || raw === \'standalone\' ? raw : \'edit\'')
    expect(source).toContain('query.view = \'compare\'')
    expect(source).toContain('@click="setPreviewView(\'compare\')"')
    expect(source).toContain('title="Compare Tailwind"')
    expect(source).toContain('Compare Tailwind')
    expect(source).toContain('data-oem-tailwind-compare-view="true"')
    expect(source).toContain('sandbox="allow-scripts"')
    expect(source).toContain('https://cdn.tailwindcss.com')
    expect(source).toContain('tailwind.config')
    expect(source).toContain(':srcdoc="tailwindCompareSrcdoc(tailwindCompareOriginalHtml(section), \'Original capture\', section)"')
    expect(source).toContain(':srcdoc="tailwindCompareSrcdoc(tailwindCompareConvertedHtml(section), \'Converted Tailwind\', section)"')
    expect(source).not.toContain('<div class="frame-label">$' + '{safeLabel}</div>$' + '{body}')
    expect(source).toContain('function styleGuideFontCss(): string')
    expect(source).toContain('function styleGuideFontFaces(): StyleGuideFontFace[]')
    expect(source).toContain('const typography = styleGuideTokens.value?.typography')
    expect(source).toContain('typography?.font_faces')
    expect(source).toContain('typography?.font_cdn_urls')
    expect(source).toContain('styleGuideTokens.value?.typography?.font_primary')
    expect(source).not.toContain('HOSTED_OEM_FONT_FACES')
    expect(source).not.toContain('MMC-Regular.woff2')
    expect(source).toContain('mappedDeclarations(section)')
    expect(source).toContain('computedDeclarations(section)')
    expect(source).toContain('function hasComputedDeclarationStats(section: any): boolean')
    expect(source).toContain('function compareMappingSummary(section: any): string')
    expect(source).toContain('No computed snapshots')
    expect(source).toContain('v-if="hasComputedDeclarationStats(section)"')
    expect(source).toContain('function compareReadinessLabel(section: any): string')
    expect(source).toContain('function compareReadinessClass(section: any): string')
    expect(source).toContain('function comparePageReadinessSummary(): { ready: number, review: number, incomplete: number, total: number }')
    expect(source).toContain('function comparePageReadinessLabel(): string')
    expect(source).toContain('function comparePageReadinessClass(): string')
    expect(source).toContain('Page ready')
    expect(source).toContain('Action required')
    expect(source).toContain('No converted sections')
    expect(source).toContain('comparePageReadinessLabel()')
    expect(source).toContain('comparePageReadinessClass()')
    expect(source).toContain('comparePageReadinessSummary().ready')
    expect(source).toContain('comparePageReadinessSummary().review')
    expect(source).toContain('comparePageReadinessSummary().incomplete')
    expect(source).toContain('Capture incomplete')
    expect(source).toContain('Needs review')
    expect(source).toContain('Ready')
    expect(source).toContain('compareReadinessLabel(section)')
    expect(source).toContain('compareReadinessClass(section)')
    expect(source).toContain('function computedSnapshotCount(section: any): number')
    expect(source).toContain('{{ computedSnapshotCount(section) }} snapshots')
    expect(source).toContain('v-if="hasTailwindLeftoverCss(section)"')
    expect(source).toContain('Leftover CSS')
    expect(source).toContain('tailwindLeftoverCss(section)')
    expect(source).toContain('v-if="hasUnsupportedDeclarationSamples(section)"')
    expect(source).toContain('Unmapped Declarations')
    expect(source).toContain('unsupportedDeclarationSamples(section)')
    expect(source).toContain('function compareTemplateSummary(section: any): string')
    expect(source).toContain('compareTemplateSummary(section)')
    expect(source).toContain('section?._tailwind_conversion?.parity_risks')
  })

  it('preserves unsaved converted sections when switching preview views', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')
    const setPreviewViewFunction = source.slice(
      source.indexOf('function setPreviewView(view: PreviewView)'),
      source.indexOf('function tailwindSectionSource(section: any): string'),
    )

    expect(setPreviewViewFunction).toContain('replacePreviewViewQuery(view)')
    expect(setPreviewViewFunction).not.toContain('router.replace')
    expect(source).toContain('function replacePreviewViewQuery(view: PreviewView)')
    expect(source).toContain('window.history.replaceState')
    expect(source).toContain('preserve unsaved converted sections')
  })

  it('adds a standalone HTML view that scopes captured sections', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('const isStandaloneView = computed(() => previewView.value === \'standalone\')')
    expect(source).toContain('@click="setPreviewView(\'standalone\')"')
    expect(source).toContain('title="Standalone HTML"')
    expect(source).toContain('function buildStandaloneHtml(): string')
    expect(source).toContain('scopeOemSection(')
    expect(source).toContain('data-section-id="')
    expect(source).toContain('sandbox="allow-scripts"')
    expect(source).toContain(':srcdoc="buildStandaloneHtml()"')
    expect(source).toContain('function openStandaloneHtml()')
    expect(source).toContain('new Blob([html], { type: \'text/html\' })')
    expect(source).toContain('window.open(url, \'_blank\')')
  })

  it('does not call the admin style guide endpoint for production previews', () => {
    const source = readFileSync(new URL('./[slug].vue', import.meta.url), 'utf8')

    expect(source).toContain('function shouldLoadStyleGuideForPreview(view: PreviewView): boolean')
    expect(source).toContain('return view === \'compare\'')
    expect(source).toContain('watch([oemId, previewView], async ([nextOemId, nextPreviewView])')
    expect(source).toContain('if (!shouldLoadStyleGuideForPreview(nextPreviewView))')
    expect(source).not.toContain('watch(oemId, async (nextOemId)')
  })
})
