// One-shot: fetches the pinned Alpine CSP build and writes it as a TS string module.
// Re-run only to bump ALPINE_VERSION; the output is committed.
import { writeFileSync } from 'node:fs';

const ALPINE_VERSION = '3.14.9';
const url = `https://cdn.jsdelivr.net/npm/@alpinejs/csp@${ALPINE_VERSION}/dist/cdn.min.js`;

const res = await fetch(url);
if (!res.ok) {
  console.error(`fetch failed: ${res.status} ${url}`);
  process.exit(1);
}
const code = await res.text();
if (!code.includes('Alpine')) {
  console.error('downloaded file does not look like Alpine');
  process.exit(1);
}

const banner = `/**
 * Vendored Alpine.js CSP build v${ALPINE_VERSION} — generated by scripts/vendor-alpine.mjs.
 * Do not edit by hand. The CSP build evaluates no inline expressions (no unsafe-eval),
 * so it is safe under strict tenant Content-Security-Policies.
 */
export const ALPINE_CSP_VERSION = '${ALPINE_VERSION}';
export const ALPINE_CSP_JS: string = `;

writeFileSync(
  new URL('../src/design/clone-runtime/alpine-csp.ts', import.meta.url),
  banner + JSON.stringify(code) + ';\n',
);
console.log(`wrote src/design/clone-runtime/alpine-csp.ts (${code.length} bytes, v${ALPINE_VERSION})`);
