import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ComponentGenerator, type BespokeComponentResult } from './component-generator';
import type { OemDesignProfile, PageSection } from '../oem/types';
import type { AiRouter } from '../ai/router';

describe('ComponentGenerator', () => {
  // -----------------------------------------------------------------------
  // Shared fixtures
  // -----------------------------------------------------------------------
  const mockR2Put = vi.fn().mockResolvedValue(undefined);
  const mockR2Bucket = { put: mockR2Put } as unknown as R2Bucket;

  const mockRoute = vi.fn();
  const mockAiRouter = { route: mockRoute } as unknown as AiRouter;

  let generator: ComponentGenerator;

  const makeProfile = (overrides: Partial<OemDesignProfile['brand_tokens']> = {}): OemDesignProfile => ({
    brand_tokens: {
      primary_color: '#c3002f',
      secondary_colors: ['#1a1a1a', '#f5f5f5'],
      font_family: 'KiaSignature, sans-serif',
      border_radius: '8px',
      button_style: 'rounded',
      ...overrides,
    },
    extraction_hints: {
      hero_selectors: [],
      gallery_selectors: [],
      tab_selectors: [],
      known_failures: [],
      bot_detection: 'none',
      wait_ms_after_load: 2000,
    },
  } as OemDesignProfile);

  const makeSection = (overrides: Partial<PageSection> = {}): PageSection => ({
    type: 'feature-cards',
    id: 'sec-001',
    order: 2,
    heading: 'Key Features',
    cards: [],
    ...overrides,
  } as unknown as PageSection);

  beforeEach(() => {
    vi.clearAllMocks();
    generator = new ComponentGenerator({ aiRouter: mockAiRouter, r2Bucket: mockR2Bucket });
  });

  // -----------------------------------------------------------------------
  // buildBrandContext
  // -----------------------------------------------------------------------
  describe('buildBrandContext (private)', () => {
    const buildBrandContext = (profile: OemDesignProfile) =>
      (generator as any).buildBrandContext(profile);

    it('includes primary color', () => {
      const ctx = buildBrandContext(makeProfile());
      expect(ctx).toContain('Primary color: #c3002f');
    });

    it('includes secondary colors', () => {
      const ctx = buildBrandContext(makeProfile());
      expect(ctx).toContain('Secondary colors: #1a1a1a, #f5f5f5');
    });

    it('includes font family', () => {
      const ctx = buildBrandContext(makeProfile());
      expect(ctx).toContain('Font family: KiaSignature, sans-serif');
    });

    it('includes border radius', () => {
      const ctx = buildBrandContext(makeProfile());
      expect(ctx).toContain('Border radius: 8px');
    });

    it('includes button style', () => {
      const ctx = buildBrandContext(makeProfile());
      expect(ctx).toContain('Button style: rounded');
    });

    it('returns fallback message when all tokens are empty', () => {
      const profile = makeProfile({
        primary_color: '',
        secondary_colors: [],
        font_family: '',
        border_radius: '',
        button_style: '',
      });
      // secondary_colors is empty array so length > 0 is false
      // primary_color, font_family, border_radius, button_style are empty strings (falsy)
      const ctx = buildBrandContext(profile);
      expect(ctx).toBe('No brand tokens available — use neutral automotive styling.');
    });

    it('omits lines for missing individual tokens', () => {
      const profile = makeProfile({
        primary_color: '#ff0000',
        secondary_colors: [],
        font_family: '',
        border_radius: '',
        button_style: '',
      });
      const ctx = buildBrandContext(profile);
      expect(ctx).toContain('Primary color: #ff0000');
      expect(ctx).not.toContain('Secondary');
      expect(ctx).not.toContain('Font family');
      expect(ctx).not.toContain('Border radius');
      expect(ctx).not.toContain('Button style');
    });
  });

  // -----------------------------------------------------------------------
  // buildHtml
  // -----------------------------------------------------------------------
  describe('buildHtml (private)', () => {
    const buildHtml = (sectionType: string, template: string, description?: string) =>
      (generator as any).buildHtml(sectionType, template, description);

    it('wraps template with HTML comment containing description', () => {
      const html = buildHtml('hero', '<div>Hello</div>', 'Hero banner component');
      expect(html).toBe('<!-- Hero banner component — Auto-generated by ComponentGenerator -->\n<div>Hello</div>');
    });

    it('uses fallback description when none provided', () => {
      const html = buildHtml('tabs', '<div>Tabs</div>');
      expect(html).toBe('<!-- Bespoke tabs section — Auto-generated by ComponentGenerator -->\n<div>Tabs</div>');
    });

    it('preserves multiline template content', () => {
      const template = '<div x-data="{open: false}">\n  <button @click="open = !open">Toggle</button>\n</div>';
      const html = buildHtml('accordion', template, 'Accordion');
      expect(html).toContain(template);
      expect(html.split('\n').length).toBe(4); // comment + 3 template lines
    });
  });

  // -----------------------------------------------------------------------
  // generateComponent — success path
  // -----------------------------------------------------------------------
  describe('generateComponent', () => {
    it('returns success with r2_key and template on valid AI response', async () => {
      mockRoute.mockResolvedValue({
        content: JSON.stringify({
          template: '<div x-data="{}">Bespoke</div>',
          description: 'Test component',
        }),
        usage: { total_tokens: 1200 },
      });

      const result = await generator.generateComponent(
        'kia-au',
        makeSection(),
        makeProfile(),
      );

      expect(result.success).toBe(true);
      expect(result.r2_key).toMatch(/^components\/kia-au\/bespoke-feature-cards-\d+\.html$/);
      expect(result.template_html).toBe('<div x-data="{}">Bespoke</div>');
      expect(result.tokens_used).toBe(1200);
      expect(result.cost_usd).toBeCloseTo(1200 * 0.000009, 6);
      expect(result.error).toBeUndefined();
    });

    it('stores the generated HTML in R2 with correct metadata', async () => {
      mockRoute.mockResolvedValue({
        content: JSON.stringify({ template: '<section>OK</section>', description: 'Test' }),
        usage: { total_tokens: 500 },
      });

      await generator.generateComponent('nissan-au', makeSection({ type: 'hero', id: 'h-1' } as any), makeProfile());

      expect(mockR2Put).toHaveBeenCalledTimes(1);
      const [key, body, options] = mockR2Put.mock.calls[0];
      expect(key).toMatch(/^components\/nissan-au\/bespoke-hero-\d+\.html$/);
      expect(body).toContain('<!-- Test');
      expect(body).toContain('<section>OK</section>');
      expect(options.httpMetadata.contentType).toBe('text/html');
      expect(options.customMetadata.oem_id).toBe('nissan-au');
      expect(options.customMetadata.section_type).toBe('hero');
      expect(options.customMetadata.section_id).toBe('h-1');
    });

    it('passes screenshot to AI router when provided', async () => {
      mockRoute.mockResolvedValue({
        content: JSON.stringify({ template: '<div>X</div>' }),
        usage: { total_tokens: 100 },
      });

      await generator.generateComponent('ford-au', makeSection(), makeProfile(), 'base64screenshot');

      const routeCall = mockRoute.mock.calls[0][0];
      expect(routeCall.imageBase64).toBe('base64screenshot');
      expect(routeCall.imageMimeType).toBe('image/jpeg');
    });

    it('does not pass imageMimeType when no screenshot', async () => {
      mockRoute.mockResolvedValue({
        content: JSON.stringify({ template: '<div>X</div>' }),
        usage: { total_tokens: 100 },
      });

      await generator.generateComponent('ford-au', makeSection(), makeProfile());

      const routeCall = mockRoute.mock.calls[0][0];
      expect(routeCall.imageBase64).toBeUndefined();
      expect(routeCall.imageMimeType).toBeUndefined();
    });

    // -----------------------------------------------------------------------
    // Error paths
    // -----------------------------------------------------------------------
    it('treats non-JSON response as raw template HTML (last-resort fallback)', async () => {
      mockRoute.mockResolvedValue({
        content: 'not json at all',
        usage: { total_tokens: 300 },
      });

      const result = await generator.generateComponent('kia-au', makeSection(), makeProfile());

      // Last-resort fallback wraps raw text as template
      expect(result.success).toBe(true);
      expect(result.tokens_used).toBe(300);
    });

    it('returns error when response JSON lacks template field', async () => {
      mockRoute.mockResolvedValue({
        content: JSON.stringify({ description: 'No template here' }),
        usage: { total_tokens: 200 },
      });

      const result = await generator.generateComponent('kia-au', makeSection(), makeProfile());

      expect(result.success).toBe(false);
      expect(result.error).toBe('Response missing "template" field');
    });

    it('catches exceptions from aiRouter and returns error result', async () => {
      mockRoute.mockRejectedValue(new Error('API timeout'));

      const result = await generator.generateComponent('kia-au', makeSection(), makeProfile());

      expect(result.success).toBe(false);
      expect(result.tokens_used).toBe(0);
      expect(result.cost_usd).toBe(0);
      expect(result.error).toBe('API timeout');
    });

    it('catches non-Error exceptions gracefully', async () => {
      mockRoute.mockRejectedValue('string error');

      const result = await generator.generateComponent('kia-au', makeSection(), makeProfile());

      expect(result.success).toBe(false);
      expect(result.error).toBe('string error');
    });

    it('sends correct taskType and requireJson in route request', async () => {
      mockRoute.mockResolvedValue({
        content: JSON.stringify({ template: '<div/>' }),
        usage: { total_tokens: 50 },
      });

      await generator.generateComponent('mazda-au', makeSection(), makeProfile());

      const routeCall = mockRoute.mock.calls[0][0];
      expect(routeCall.taskType).toBe('bespoke_component');
      expect(routeCall.oemId).toBe('mazda-au');
      expect(routeCall.requireJson).toBe(true);
      expect(routeCall.maxTokens).toBe(4096);
    });
  });
});
