-- Insert used vehicle from dealer inventory
-- Source: Brighton Suzuki via carsales.com.au export

INSERT INTO products (
  id,
  oem_id,
  external_key,
  title,
  subtitle,
  body_type,
  fuel_type,
  availability,
  price_amount,
  price_currency,
  price_type,
  price_qualifier,
  engine_size,
  cylinders,
  transmission,
  gears,
  drive,
  doors,
  seats,
  primary_image_r2_key,
  gallery_image_count,
  meta_json,
  last_seen_at,
  created_at,
  updated_at
) VALUES (
  'aa309874-604e-48ce-af78-bb54198c051f',
  'suzuki-au',
  'OAG-AD-25294293',
  '2024 Suzuki S-Cross Auto',
  'JYB Series',
  'SUV',
  'Petrol',
  'For Sale',
  32990,
  'AUD',
  'DAP',
  'Used',
  '1373',
  4,
  'Sports Automatic',
  6,
  'Front Wheel Drive',
  5,
  5,
  NULL,  -- Image needs R2 upload: https://carsales.pxcrush.net/cars/dealer/6try2kctwiflu4lgs3njbl5uh.jpg
  25,
  '{
    "vin": "TSMJYAA2S00B60698",
    "registration": "2DB7FN",
    "stock_number": "372395",
    "odometer_km": 33,
    "build_year": 2024,
    "exterior_colour": "Cool White",
    "exterior_colour_generic": "White",
    "location": {
      "suburb": "Brighton East",
      "state": "Victoria",
      "postcode": "3187",
      "lat": -37.917343,
      "lng": 145.016678
    },
    "source": "carsales",
    "network_id": "OAG-AD-25294293",
    "specification_code": "AUVSUZU2024AEAK",
    "specification_source": "REDBOOK"
  }'::jsonb,
  '2026-02-10 00:58:45+00',
  '2025-11-30 06:32:49+00',
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  price_amount = EXCLUDED.price_amount,
  availability = EXCLUDED.availability,
  engine_size = EXCLUDED.engine_size,
  cylinders = EXCLUDED.cylinders,
  transmission = EXCLUDED.transmission,
  gears = EXCLUDED.gears,
  drive = EXCLUDED.drive,
  doors = EXCLUDED.doors,
  seats = EXCLUDED.seats,
  meta_json = EXCLUDED.meta_json,
  last_seen_at = EXCLUDED.last_seen_at,
  updated_at = NOW();
